In [ ]:
'''
Mini Exercise

Diberikan dua buah data
reddit_opinion_climate_change.csv
reddit_opinion_climate_change_author.csv
Lakukanlah concat pada kedua data tersebut.
Sebelum dilakukan concat, jadikan 'comment_id' sebagai index
'''

In [1]:
# import library 
import pandas as pd

In [2]:
# read data reddit_opinion_climate_change.csv
opinion = pd.read_csv("D:\\python\\Python for ML n DS\\python_data engineering\\pacmann_datasets\\week 3\\reddit_opinion_climate_change.csv")

# View top 5 data
opinion.head()

,comment_id,created_time,self_text,subreddit,score
0,kbbycqo,2023-11-29 23:28:59,"Yeah, I understood that, can you link to your ...",climatechange,1
1,kbbxiah,2023-11-29 23:23:01,It's Robotics;Notes all over again.,worldnews,1
2,kbbx4td,2023-11-29 23:20:24,Technology improves at an exponential rate.,changemyview,1
3,kbbwzou,2023-11-29 23:19:25,Of course they do. Fuck the GOP. Seriously FUC...,politics,1
4,kbbwbin,2023-11-29 23:14:47,"There's nothing ""natural"" about it. Why would ...",climatechange,1

In [3]:
# read data reddit_opinion_climate_change_author.csv
opinion_author = pd.read_csv("D:\\python\\Python for ML n DS\\python_data engineering\\pacmann_datasets\\week 3\\reddit_opinion_climate_change_author.csv")

# View top 5 data
opinion_author.head()

  comment_id           author_name
0    kb9ouxb  Reasonable_Cover_804
1    kb9ix6s     Wave_of_Anal_Fury
2    kb9jcsb        SadPanthersFan
3    kbbkdsh           mrjigglyman
4    kbbiwxi            drkstlth01

In [4]:
# From reddit_opinion_climate_change.csv data, set "comment_id" become index 
opinion.set_index('comment_id', inplace = True)

# View 5 top data 
opinion.head()

,created_time,self_text,subreddit,score
comment_id,,,,
kbbycqo,2023-11-29 23:28:59,"Yeah, I understood that, can you link to your ...",climatechange,1
kbbxiah,2023-11-29 23:23:01,It's Robotics;Notes all over again.,worldnews,1
kbbx4td,2023-11-29 23:20:24,Technology improves at an exponential rate.,changemyview,1
kbbwzou,2023-11-29 23:19:25,Of course they do. Fuck the GOP. Seriously FUC...,politics,1
kbbwbin,2023-11-29 23:14:47,"There's nothing ""natural"" about it. Why would ...",climatechange,1

In [5]:
# From reddit_opinion_climate_change_author.csv data, set "comment_id" become index 
opinion_author.set_index('comment_id', inplace = True)

# View 5 top data 
opinion_author.head()

                     author_name
comment_id
kb9ouxb     Reasonable_Cover_804
kb9ix6s        Wave_of_Anal_Fury
kb9jcsb           SadPanthersFan
kbbkdsh              mrjigglyman
kbbiwxi               drkstlth01

In [7]:
# Create new dataframe baru to save the concat result
opinion_concat = pd.concat([opinion, opinion_author], 
                            axis = 1, 
                            join = 'inner'
                          )

# View 5 top data the concat result
opinion_concat.head()

,created_time,self_text,subreddit,score,author_name
comment_id,,,,,
kbbycqo,2023-11-29 23:28:59,"Yeah, I understood that, can you link to your ...",climatechange,1,Lumi_Tonttu
kbbxiah,2023-11-29 23:23:01,It's Robotics;Notes all over again.,worldnews,1,Yezzik
kbbx4td,2023-11-29 23:20:24,Technology improves at an exponential rate.,changemyview,1,SeaBearsFoam
kbbwzou,2023-11-29 23:19:25,Of course they do. Fuck the GOP. Seriously FUC...,politics,1,Onthemightof
kbbwbin,2023-11-29 23:14:47,"There's nothing ""natural"" about it. Why would ...",climatechange,1,Jake0024