In [ ]:
''' 
Mini Exercise

Diberikan sebuah data: 
Netflix_TV_Shows_and_Movies.csv
Lakukan grouping untuk mengelompokkan data berdasarkan: 
type
age_certification
Hitunglah jumlah masing-masing data.
Tampilkan data:
type: MOVIE
age_certification: NC-17
'''

In [1]:
# import library 
import pandas as pd

In [5]:
# read csv data 
netflix_data = pd.read_csv("D:\\python\\Python for ML n DS\\python_data engineering\\pacmann_datasets\\week 3\\Netflix_TV_Shows_and_Movies.csv") 

# view 5 top data
netflix_data

,index,id,title,type,description,release_year,age_certification,runtime,imdb_id,imdb_score,imdb_votes
0,0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,tt0075314,8.3,795222.0
1,1,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,tt0071853,8.2,530877.0
2,2,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,tt0079470,8.0,392419.0
3,3,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,tt0070047,8.1,391942.0
4,4,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,tt0063929,8.8,72895.0
...,...,...,...,...,...,...,...,...,...,...,...
5278,5278,tm1040816,Momshies! Your Soul is Mine,MOVIE,Three women with totally different lives accid...,2021,NaN,108,tt14412240,5.8,26.0
5279,5279,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,tt13857480,6.9,39.0
5280,5280,tm1045018,Clash,MOVIE,A man from Nigeria returns to his family in Ca...,2021,NaN,88,tt14620732,6.5,32.0
5281,5281,tm1098060,Shadow Parties,MOVIE,A family faces destruction in a long-running c...,2021,NaN,116,tt10168094,6.2,9.0
5282,5282,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,0,tt13711094,8.8,16.0

In [6]:
# Create object to save the grouping result 
# Grouping based on type and age_certification columns
netflix_type_agecert = netflix_data.groupby(by = ['type', 'age_certification']) 

netflix_type_agecert

In [7]:
# View the amount of data for each type and age_certification 
netflix_type_agecert.size()

type   age_certification
MOVIE  G                    105
       NC-17                 13
       PG                   238
       PG-13                424
       R                    548
SHOW   TV-14                436
       TV-G                  72
       TV-MA                792
       TV-PG                172
       TV-Y                  94
       TV-Y7                104
dtype: int64

In [14]:
# View data with type = MOVIE and age_certification = NC-17
netflix_type_agecert.get_group(('MOVIE', 'NC-17'))

,index,id,title,type,description,release_year,age_certification,runtime,imdb_id,imdb_score,imdb_votes
570,570,tm49865,Aamir,MOVIE,A doctor of Indian origin returning to Mumbai ...,2008,NC-17,99,tt1241195,7.6,11241.0
692,692,tm60844,Berserk: The Golden Age Arc I - The Egg of the...,MOVIE,"Guts, an immensely strong sword-for-hire, has ...",2012,NC-17,76,tt2311238,7.5,12278.0
794,794,tm164090,Lavell Crawford: Can a Brother Get Some Love?,MOVIE,"""Last Comic Standing"" runner-up Lavell Crawfor...",2011,NC-17,90,tt2084872,6.9,230.0
963,963,tm167944,Berserk: The Golden Age Arc III - The Advent,MOVIE,A year has passed since Guts parted ways with ...,2013,NC-17,110,tt2358913,7.8,9942.0
1221,1221,tm245271,Gantz:O,MOVIE,"Somewhere in Tokyo, there is a room. In that r...",2016,NC-17,95,tt5923962,7.1,14501.0
1945,1945,tm217228,Death Note,MOVIE,A young man comes to possess a supernatural no...,2017,NC-17,101,tt1241317,4.5,83519.0
2221,2221,tm408941,Mercury 13,MOVIE,"After rigorous testing in 1961, a small group ...",2018,NC-17,79,tt8139850,6.9,1160.0
2404,2404,tm429382,Nappily Ever After,MOVIE,"After an accident at the hair salon, Violet re...",2018,NC-17,100,tt0365545,6.4,9139.0
2462,2462,tm515157,Point Blank,MOVIE,A top spy must clear his name when he faces mi...,2017,NC-17,86,tt2499472,5.7,14184.0
2490,2490,tm440678,Revenger,MOVIE,Hell-bent on avenging the murder of his family...,2018,NC-17,102,tt9426186,5.7,4252.0
3406,3406,tm933375,Cuties,MOVIE,"Amy, an 11-year-old girl, joins a group of dan...",2020,NC-17,96,tt9196192,3.3,30030.0
3510,3510,tm922532,Freaks Ã¢â‚¬â€œ You're One of Us,MOVIE,After having a chance encounter with a mysteri...,2020,NC-17,93,tt12875782,5.4,5809.0
3653,3653,tm283581,Super Deluxe,MOVIE,"An unfaithful newly-wed wife, an estranged fat...",2019,NC-17,176,tt7019942,8.4,13680.0